# Generated by Django 6.1.1 on 2026-09-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(db_index=True, help_text='YouTube tomonidan berilgan noyob kanal ID (masalan: UC...)', max_length=64, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('custom_url', models.CharField(blank=True, default='', max_length=128)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber_count', models.BigIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('api_key', models.CharField(blank=True, default='', help_text='Kanal uchun maxsus YouTube API kaliti (ixtiyoriy)', max_length=255)),
                ('owner', models.ForeignKey(help_text="Egasi bo'lgan foydalanuvchi", on_delete=django.db.models.deletion.CASCADE, related_name='youtube_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Kanal',
                'verbose_name_plural': 'YouTube Kanallar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('items_synced', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='youtube.youtubechannel')),
            ],
            options={
                'verbose_name': 'Sinxronizatsiya Vazifasi',
                'verbose_name_plural': 'Sinxronizatsiya Vazifalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='youtube.youtubechannel')),
            ],
            options={
                'verbose_name': 'YouTube Playlist',
                'verbose_name_plural': 'YouTube Playlistlar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('view_count', models.BigIntegerField(db_index=True, default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('privacy_status', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], db_index=True, default='public', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtube.youtubechannel')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='youtube.youtubeplaylist')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videolar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='youtubechannel',
            constraint=models.UniqueConstraint(fields=('owner', 'channel_id'), name='unique_owner_channel'),
        ),
        migrations.AddConstraint(
            model_name='youtubechannel',
            constraint=models.CheckConstraint(condition=models.Q(('subscriber_count__gte', 0)), name='subscriber_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='youtubechannel',
            constraint=models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='channel_view_count_non_negative'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['channel', '-published_at'], name='youtube_you_channel_016512_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['channel', '-view_count'], name='youtube_you_channel_a9f280_idx'),
        ),
        migrations.AddConstraint(
            model_name='youtubevideo',
            constraint=models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='video_view_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='youtubevideo',
            constraint=models.CheckConstraint(condition=models.Q(('like_count__gte', 0)), name='video_like_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='youtubevideo',
            constraint=models.CheckConstraint(condition=models.Q(('comment_count__gte', 0)), name='video_comment_count_non_negative'),
        ),
    ]
