# Generated by Django 6.1.1 on 2026-09-19 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelNiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niche_name', models.CharField(help_text="Asosiy kanal mavzusi (masalan: Sun'iy Intellekt va Kelajak Texnologiyalari)", max_length=255)),
                ('description', models.TextField(help_text='Mavzuning batafsil tasnifi va maqsadli auditoriya')),
                ('tone', models.CharField(default='informative, engaging, futuristic', max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list, help_text="Asosiy SEO kalit so'zlari")),
                ('prompt_guidelines', models.TextField(blank=True, default='Har bir video 1ta mavzu doirasida, tomoshabinni jalb qiluvchi sarlavha va qiziqarli vizual prompt bilan yaratilsin.')),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='niche_strategy', to='youtube.youtubechannel')),
            ],
            options={
                'verbose_name': 'Kanal Mavzusi (Niche)',
                'verbose_name_plural': 'Kanal Mavzulari (Niches)',
            },
        ),
        migrations.CreateModel(
            name='FlowAIAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Akkaunt nomi (masalan: Flow AI Akkaunt 1)', max_length=100)),
                ('email', models.EmailField(blank=True, default='', help_text="Akkaunt emaili (agar mavjud bo'lsa)", max_length=254)),
                ('profile_dir', models.CharField(default='Default', help_text='Chrome profil katalogi (masalan: Default, Profile 1, Profile 3, Profile 4)', max_length=255)),
                ('credits_remaining', models.IntegerField(default=1000, help_text='Qolgan kreditlar miqdori')),
                ('initial_credits', models.IntegerField(default=1000, help_text='Dastlabki kredit miqdori')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flow AI Akkaunt',
                'verbose_name_plural': 'Flow AI Akkauntlar',
                'ordering': ['-credits_remaining', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('credits_remaining__gte', 0)), name='flow_ai_credits_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='VideoGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='Flow AI uchun Gemini tomonidan yaratilgan prompt')),
                ('status', models.CharField(choices=[('queued', 'Navbatda'), ('generating', 'Generatsiya qilinmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], db_index=True, default='queued', max_length=20)),
                ('video_file_path', models.CharField(blank=True, default='', max_length=500)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('credits_used', models.PositiveIntegerField(default=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_tasks', to='youtube.flowaiaccount')),
            ],
            options={
                'verbose_name': 'Video Generatsiya Vazifasi',
                'verbose_name_plural': 'Video Generatsiya Vazifalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyChannelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.BigIntegerField(default=0)),
                ('total_subscribers', models.BigIntegerField(default=0)),
                ('total_videos', models.PositiveIntegerField(default=0)),
                ('views_growth_today', models.BigIntegerField(default=0, help_text="Bugungi ko'rishlar o'sishi")),
                ('subscribers_growth_today', models.BigIntegerField(default=0, help_text="Bugungi obunachilar o'sishi")),
                ('growth_rate_percent', models.FloatField(default=0.0, help_text="Foizdagi o'sish darajasi")),
                ('telegram_report_sent', models.BooleanField(default=False)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='youtube.youtubechannel')),
            ],
            options={
                'verbose_name': 'Kunlik Statistika',
                'verbose_name_plural': 'Kunlik Statistikalar',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'date'), name='unique_channel_daily_analytic')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField(default='19:00:00')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('processing', 'Yuklanmoqda'), ('published', 'Nashr qilindi'), ('failed', 'Xatolik')], db_index=True, default='scheduled', max_length=20)),
                ('youtube_video_id', models.CharField(blank=True, default='', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_uploads', to='youtube.youtubechannel')),
                ('video_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_schedule', to='youtube.videogenerationtask')),
            ],
            options={
                'verbose_name': 'Rejalashtirilgan Yuklash',
                'verbose_name_plural': 'Rejalashtirilgan Yuklashlar',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'scheduled_date', 'scheduled_time'), name='unique_channel_schedule_slot')],
            },
        ),
    ]
