# Generated by Django 6.1.1 on 2026-09-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_channelniche_flowaiaccount_videogenerationtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowaiaccount',
            name='has_flow_credits',
            field=models.BooleanField(default=True, help_text='Ushbu akkauntda Flow AI kreditlari bormi'),
        ),
        migrations.AddField(
            model_name='flowaiaccount',
            name='has_youtube_channel',
            field=models.BooleanField(default=False, help_text='Ushbu akkauntda YouTube kanal bormi'),
        ),
        migrations.AddField(
            model_name='flowaiaccount',
            name='inspection_status',
            field=models.CharField(default='verified', help_text='Holat: verified, pending, not_found', max_length=50),
        ),
        migrations.AddField(
            model_name='flowaiaccount',
            name='last_inspected_at',
            field=models.DateTimeField(blank=True, help_text='Oxirgi marta brauzer orqali tekshirilgan vaqt', null=True),
        ),
        migrations.AddField(
            model_name='flowaiaccount',
            name='youtube_channel_id',
            field=models.CharField(blank=True, default='', help_text='YouTube kanal ID', max_length=100),
        ),
        migrations.AddField(
            model_name='flowaiaccount',
            name='youtube_channel_name',
            field=models.CharField(blank=True, default='', help_text='YouTube kanal nomi', max_length=255),
        ),
        migrations.AddField(
            model_name='flowaiaccount',
            name='youtube_subscribers',
            field=models.BigIntegerField(default=0, help_text='YouTube obunachilar soni'),
        ),
        migrations.AlterField(
            model_name='flowaiaccount',
            name='profile_dir',
            field=models.CharField(default='Default', help_text='Chrome profil katalogi (masalan: Default, Profile 1, Profile 3, Profile 4, Profile 6)', max_length=255),
        ),
    ]
