# Generated by Django 6.1.1 on 2026-09-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_flowaiaccount_has_flow_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledupload',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Tasdiqlash kutilmoqda'), ('scheduled', 'Rejalashtirilgan'), ('processing', 'Yuklanmoqda'), ('published', 'Nashr qilindi'), ('failed', 'Xatolik')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
